language: node_js
node_js:
  - "4.3.2"
deploy:
  - provider: lambda
    function_name: "repl"
    role: $REPL_LAMBDA_ROLE
    runtime: "nodejs6.10"
    module_name: "repl"
    handler_name: "handler"
    memory_size: "512"
    timeout: "10"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
      repo: "backbench/bbvm"
      branch: "stage-alpha"
  - provider: lambda
    function_name: "bbvm"
    role: $BBVM_LAMBDA_ROLE
    runtime: "nodejs6.10"
    module_name: "index"
    handler_name: "handler"
    memory_size: "1024"
    timeout: "15"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
      repo: "backbench/bbvm"
      branch: "stage-alpha"
